## Global Document Indices
This is the file that indicates the bounds of each document (bucketed using function "bucket_documents" in olmo_core.data.utils) 

In [308]:
from olmo_core.data.utils import load_array_slice_into_tensor
import numpy as np

file_path = '/home/morg/students/gottesman3/knowledge-analysis-suite/OLMo-core/dataset-cache/dataset-common/bucketed-doc-indices-059058d45dc5ae8dedb089893239e458f86f2af4944b3ddc8ca6c3d10d64580c.npy'
doc_indices = load_array_slice_into_tensor(file_path, 0, 1000000, np.uint32)

In [309]:
len(doc_indices)

139834

In [310]:
import torch

# Create list of start, end pairs
start_end_pairs = [(doc_indices[i].item(), doc_indices[i+1].item()) 
                   for i in range(0, len(doc_indices) - 1, 2)]


In [418]:
doc_mmemap = np.memmap('/home/morg/students/gottesman3/knowledge-analysis-suite/dolma/python/wikipedia_vsl/part-00-00000.npy', dtype=np.int32, mode='r')


In [311]:
print(start_end_pairs[30805])
print(doc_mmemap[start_end_pairs[30805][0]:start_end_pairs[30805][1]][:5])

print(start_end_pairs[9146])
print(doc_mmemap[start_end_pairs[9146][0]: start_end_pairs[9146][1]][:5])

# INDEX: 30805, input_ids first 5 tokens: tensor([   43,  5620, 39051,   616,   220])
# INDEX: 9146, input_ids first 5 tokens: tensor([   41, 28323, 27466,   689, 23535])

(23192047, 23194095)
[   43  5620 39051   616   220]
(6928740, 6930788)
[   41 28323 27466   689 23535]


## Instance Lengths

In [312]:
instance_lengths = "/home/morg/students/gottesman3/knowledge-analysis-suite/OLMo-core/dataset-cache/dataset-a467e3d28b51968cd6a61ff1615c8766c81e0697de465bf46324995390e73b27/instance-lengths.npy"
lengths = load_array_slice_into_tensor(instance_lengths, 0, 100000, np.uint16)

In [313]:
print(lengths[30805], start_end_pairs[30805][1] - start_end_pairs[30805][0])
print(lengths[9146], start_end_pairs[9146][1] - start_end_pairs[9146][0])

tensor(2048) 2048
tensor(2048) 2048


## Indices of Instances with Length (2048, 1024, 512, 256)

In [314]:
values_to_find = [2048, 1024, 512, 256]

# Get indices for each value
indices_dict = {val: torch.where(lengths == val)[0].tolist() for val in values_to_find}

In [315]:
print(len(indices_dict[2048]) + len(indices_dict[1024]) + len(indices_dict[512]) + len(indices_dict[256]))
print(len(start_end_pairs))

# This is the number of docs in the dataset, and also the same size of start_end_pairs, obviously.

69917
69917


## Indices of Instances Buckets (2048, 1024, 512, 256) Epoch == 1

In [316]:
# Use this to identify the bounds of the documents accessed in epoch_1

global_batch_indices_epoch_1 = "/home/morg/students/gottesman3/knowledge-analysis-suite/OLMo-core/dataset-cache/dataset-a467e3d28b51968cd6a61ff1615c8766c81e0697de465bf46324995390e73b27/vsl-grow-p2-1-cycle-balanced/global_batch_indices_bz32768_epoch1_seed0.npy"
global_batch_epoch_1 = load_array_slice_into_tensor(global_batch_indices_epoch_1, 0, 10000, np.uint32)

In [317]:
len(global_batch_epoch_1)

1040

In [417]:
global_batch_epoch_1

2

In [346]:
instance_indices_bucket_2048 = "/home/morg/students/gottesman3/knowledge-analysis-suite/OLMo-core/dataset-cache/dataset-a467e3d28b51968cd6a61ff1615c8766c81e0697de465bf46324995390e73b27/vsl-grow-p2-1-cycle-balanced/instance_indices_bucket2048_epoch1_seed0.npy"
instance_2048 = load_array_slice_into_tensor(instance_indices_bucket_2048, 0, 10000, np.uint32)

instance_indices_bucket_1024 = "/home/morg/students/gottesman3/knowledge-analysis-suite/OLMo-core/dataset-cache/dataset-a467e3d28b51968cd6a61ff1615c8766c81e0697de465bf46324995390e73b27/vsl-grow-p2-1-cycle-balanced/instance_indices_bucket1024_epoch1_seed0.npy"
instance_1024 = load_array_slice_into_tensor(instance_indices_bucket_1024, 0, 10000, np.uint32)

instance_indices_bucket_512 = "/home/morg/students/gottesman3/knowledge-analysis-suite/OLMo-core/dataset-cache/dataset-a467e3d28b51968cd6a61ff1615c8766c81e0697de465bf46324995390e73b27/vsl-grow-p2-1-cycle-balanced/instance_indices_bucket512_epoch1_seed0.npy"
instance_512 = load_array_slice_into_tensor(instance_indices_bucket_512, 0, 100000, np.uint32)

instance_indices_bucket_256 = "/home/morg/students/gottesman3/knowledge-analysis-suite/OLMo-core/dataset-cache/dataset-a467e3d28b51968cd6a61ff1615c8766c81e0697de465bf46324995390e73b27/vsl-grow-p2-1-cycle-balanced/instance_indices_bucket256_epoch1_seed0.npy"
instance_256 = load_array_slice_into_tensor(instance_indices_bucket_256, 0, 100000, np.uint32)

In [351]:
len(instance_2048) + len(instance_1024) + len(instance_512) + len(instance_256)

69917

In [374]:
print(all(start_end_pairs[inst][1] - start_end_pairs[inst][0] == 2048 for inst in instance_2048))
print(all(start_end_pairs[inst][1] - start_end_pairs[inst][0] == 1024 for inst in instance_1024))
print(all(start_end_pairs[inst][1] - start_end_pairs[inst][0] == 512 for inst in instance_512))
print(all(start_end_pairs[inst][1] - start_end_pairs[inst][0] == 256 for inst in instance_256))

True
True
True
True


## Global Bucket Indices in Dataloader
Indices of docs in each bucket

In [386]:
bucket_2048_indices = "/home/morg/students/gottesman3/knowledge-analysis-suite/OLMo-core/dataset-cache/dataset-a467e3d28b51968cd6a61ff1615c8766c81e0697de465bf46324995390e73b27/bucket2048-indices.npy"
bucket_2048_indices = load_array_slice_into_tensor(bucket_2048_indices, 0, 100000, np.uint32)

bucket_1024_indices = "/home/morg/students/gottesman3/knowledge-analysis-suite/OLMo-core/dataset-cache/dataset-a467e3d28b51968cd6a61ff1615c8766c81e0697de465bf46324995390e73b27/bucket1024-indices.npy"
bucket_1024_indices = load_array_slice_into_tensor(bucket_1024_indices, 0, 100000, np.uint32)

bucket_512_indices = "/home/morg/students/gottesman3/knowledge-analysis-suite/OLMo-core/dataset-cache/dataset-a467e3d28b51968cd6a61ff1615c8766c81e0697de465bf46324995390e73b27/bucket512-indices.npy"
bucket_512_indices = load_array_slice_into_tensor(bucket_512_indices, 0, 100000, np.uint32)

bucket_256_indices = "/home/morg/students/gottesman3/knowledge-analysis-suite/OLMo-core/dataset-cache/dataset-a467e3d28b51968cd6a61ff1615c8766c81e0697de465bf46324995390e73b27/bucket256-indices.npy"
bucket_256_indices = load_array_slice_into_tensor(bucket_256_indices, 0, 100000, np.uint32)


In [391]:
len(bucket_2048_indices) + len(bucket_1024_indices) + len(bucket_512_indices) + len(bucket_256_indices)

69917

In [398]:
print(bucket_2048_indices)
print(instance_2048)

tensor([    5,    15,    16,  ..., 69862, 69871, 69904])
tensor([52251, 12192,   834,  ..., 53179, 56377, 50864])


In [399]:
print(bucket_1024_indices)
print(instance_1024)

tensor([    2,     6,     8,  ..., 69877, 69891, 69913])
tensor([37302, 33164,   610,  ..., 67671, 29041,  3725])


In [400]:
print(bucket_512_indices)
print(instance_512)

tensor([    3,     9,    11,  ..., 69911, 69914, 69915])
tensor([28241, 35420, 66787,  ..., 61114, 43320, 61648])


In [401]:
print(bucket_256_indices)
print(instance_256)

tensor([    0,     1,     4,  ..., 69910, 69912, 69916])
tensor([18882, 52417,  4195,  ..., 10923, 65322, 16128])


In [ ]:
print(all(doc_index in bucket_2048_indices for doc_index in indices_dict[2048]))
print(all(doc_index in indices_dict[2048] for doc_index in bucket_2048_indices))
print(all(doc_index in instance_2048 for doc_index in indices_dict[2048]))
print(all(doc_index in indices_dict[2048] for doc_index in instance_2048))

print(all(doc_index in bucket_1024_indices for doc_index in indices_dict[1024]))
print(all(doc_index in indices_dict[1024] for doc_index in bucket_1024_indices))
print(all(doc_index in instance_1024 for doc_index in indices_dict[1024]))
print(all(doc_index in indices_dict[1024] for doc_index in instance_1024))

print(all(doc_index in bucket_512_indices for doc_index in indices_dict[512]))
print(all(doc_index in indices_dict[512] for doc_index in bucket_512_indices))
print(all(doc_index in instance_512 for doc_index in indices_dict[512]))
print(all(doc_index in indices_dict[512] for doc_index in instance_512))

print(all(doc_index in bucket_256_indices for doc_index in indices_dict[256]))
print(all(doc_index in indices_dict[256] for doc_index in bucket_256_indices))
print(all(doc_index in instance_256 for doc_index in indices_dict[256]))
print(all(doc_index in indices_dict[256] for doc_index in instance_256))


True
True
True
True
True
True
True
True
True
